/* ============================================================
   PhysDeck — content data
   Cambridge International AS Physics 9702 (2025-2027 syllabus)
   ------------------------------------------------------------
   Card schema:
     {
       id:         "kin-04",
       topic:      "Kinematics",
       type:       "formula" | "definition" | "theorem" | "unit",
       term:       "Equation of motion (no time)",
       asks:       "Give the equation of motion linking v, u, a and s",  // optional
                   // The instruction shown on the card front. Omit it and one
                   // is derived from `type`. Use it wherever the term alone
                   // does not pin down which formula (or which unit) is wanted.
       graph:      "vt-area",   // optional — key into GRAPHS in graphs.js, drawn
                   // on the revealed side under the answer.
       answer:     "v² = u² + 2as",
       detail:     "Why / when it is used.",
       difficulty: 1 | 2 | 3
     }
   ============================================================ */

const TOPICS = [
  { id: "units",  name: "Physical Quantities & Units", short: "Units",         color: "#4cc9f0" },
  { id: "kin",    name: "Kinematics",                  short: "Kinematics",    color: "#4895ef" },
  { id: "dyn",    name: "Dynamics",                    short: "Dynamics",      color: "#5a6cf5" },
  { id: "frc",    name: "Forces, Density & Pressure",  short: "Forces",        color: "#9d4edd" },
  { id: "nrg",    name: "Work, Energy & Power",        short: "Energy",        color: "#f72585" },
  { id: "def",    name: "Deformation of Solids",       short: "Deformation",   color: "#ff8c42" },
  { id: "wav",    name: "Waves",                       short: "Waves",         color: "#06d6a0" },
  { id: "sup",    name: "Superposition",               short: "Superposition", color: "#2ec4b6" },
  { id: "ele",    name: "Electricity",                 short: "Electricity",   color: "#ffd166" },
  { id: "dc",     name: "D.C. Circuits",               short: "D.C. Circuits", color: "#ef476f" },
  { id: "nuc",    name: "Particle & Nuclear Physics",  short: "Nuclear",       color: "#c77dff" }
];

const CARDS = [

  /* ---------- 1. Physical Quantities & Units ---------- */
  { id: "units-01", topic: "units", type: "definition", difficulty: 1,
    term: "Physical quantity",
    answer: "A quantity that consists of a numerical magnitude and a unit.",
    detail: "Every measured value in physics must be quoted with both parts, e.g. 9.81 m s⁻²." },
  { id: "units-02", topic: "units", type: "unit", difficulty: 1,
    term: "The seven SI base quantities",
    asks: "Name all seven",
    answer: "mass, length, time, current, temperature, amount of substance, luminous intensity",
    detail: "Only the first six are examinable at AS; every other unit is derived from them." },
  { id: "units-03", topic: "units", type: "unit", difficulty: 1,
    term: "SI base units (symbols)",
    asks: "Give the symbol for each",
    answer: "kg, m, s, A, K, mol, cd",
    detail: "Kilogram, metre, second, ampere, kelvin, mole, candela." },
  { id: "units-04", topic: "units", type: "theorem", difficulty: 2,
    term: "Homogeneity of an equation",
    answer: "Every term on both sides must have the same base units.",
    detail: "A homogeneous equation may still be wrong (a missing constant like ½), but a non-homogeneous equation is always wrong." },
  { id: "units-05", topic: "units", type: "unit", difficulty: 2,
    term: "SI prefixes: p, n, µ, m, c, d",
    asks: "Give the power of ten for each",
    answer: "10⁻¹², 10⁻⁹, 10⁻⁶, 10⁻³, 10⁻², 10⁻¹",
    detail: "pico, nano, micro, milli, centi, deci." },
  { id: "units-06", topic: "units", type: "unit", difficulty: 2,
    term: "SI prefixes: k, M, G, T",
    asks: "Give the power of ten for each",
    answer: "10³, 10⁶, 10⁹, 10¹²",
    detail: "kilo, mega, giga, tera." },
  { id: "units-07", topic: "units", type: "unit", difficulty: 2,
    term: "Newton in base units",
    asks: "Express in SI base units",
    answer: "1 N = 1 kg m s⁻²",
    detail: "From F = ma: kilogram × metre per second squared." },
  { id: "units-08", topic: "units", type: "unit", difficulty: 2,
    term: "Joule in base units",
    asks: "Express in SI base units",
    answer: "1 J = 1 kg m² s⁻²",
    detail: "From W = Fs: N m = kg m s⁻² × m." },
  { id: "units-09", topic: "units", type: "unit", difficulty: 2,
    term: "Watt in base units",
    asks: "Express in SI base units",
    answer: "1 W = 1 kg m² s⁻³",
    detail: "From P = W/t: J s⁻¹." },
  { id: "units-10", topic: "units", type: "unit", difficulty: 2,
    term: "Pascal in base units",
    asks: "Express in SI base units",
    answer: "1 Pa = 1 kg m⁻¹ s⁻²",
    detail: "From p = F/A: N m⁻²." },
  { id: "units-11", topic: "units", type: "definition", difficulty: 1,
    term: "Scalar quantity",
    answer: "A quantity that has magnitude only.",
    detail: "Examples: mass, time, speed, distance, energy, temperature, density, work, power, pressure." },
  { id: "units-12", topic: "units", type: "definition", difficulty: 1,
    term: "Vector quantity",
    answer: "A quantity that has both magnitude and direction.",
    detail: "Examples: displacement, velocity, acceleration, force, weight, momentum, impulse, electric field strength." },
  { id: "units-13", topic: "units", type: "formula", difficulty: 2,
    term: "Resolving a vector into components",
    asks: "Give the formula for both perpendicular components",
    answer: "Fₓ = F cosθ,  F_y = F sinθ",
    detail: "θ measured from the x-axis. The component along the direction of θ always takes the cosine." },
  { id: "units-14", topic: "units", type: "formula", difficulty: 2,
    term: "Resultant of two perpendicular vectors",
    asks: "Give the formula for the magnitude and the direction",
    answer: "R = √(Fₓ² + F_y²),  tanθ = F_y / Fₓ",
    detail: "For non-perpendicular vectors use a scale drawing, or resolve into components first and then combine." },
  { id: "units-15", topic: "units", type: "definition", difficulty: 2,
    term: "Systematic error",
    answer: "An error that shifts every reading by the same amount or the same proportion, always in the same direction.",
    detail: "Caused by faulty apparatus or a zero error. Cannot be reduced by repeating readings; it can be removed by recalibration." },
  { id: "units-16", topic: "units", type: "definition", difficulty: 2,
    term: "Random error",
    answer: "An error that causes readings to scatter either side of the true value in an unpredictable way.",
    detail: "Reduced by taking repeated readings and averaging, or by plotting a best-fit line." },
  { id: "units-17", topic: "units", type: "definition", difficulty: 2,
    term: "Precision",
    answer: "How close repeated readings are to one another.",
    detail: "A precise set of readings has a small spread. Precision says nothing about closeness to the true value." },
  { id: "units-18", topic: "units", type: "definition", difficulty: 2,
    term: "Accuracy",
    answer: "How close a reading is to the true value of the quantity.",
    detail: "Improved by removing systematic errors; precision is improved by reducing random errors." },
  { id: "units-19", topic: "units", type: "formula", difficulty: 2,
    term: "Percentage uncertainty",
    asks: "Give the formula in terms of the absolute uncertainty",
    answer: "% uncertainty = (absolute uncertainty / measured value) × 100%",
    detail: "Also called fractional uncertainty when the ×100% is left off." },
  { id: "units-20", topic: "units", type: "theorem", difficulty: 3,
    term: "Combining uncertainties: adding or subtracting",
    answer: "Add the absolute uncertainties.",
    detail: "If y = a ± b then Δy = Δa + Δb. Note that uncertainties always add, even for a subtraction." },
  { id: "units-21", topic: "units", type: "theorem", difficulty: 3,
    term: "Combining uncertainties: multiplying or dividing",
    answer: "Add the percentage (fractional) uncertainties.",
    detail: "If y = ab or a/b then Δy/y = Δa/a + Δb/b." },
  { id: "units-22", topic: "units", type: "theorem", difficulty: 3,
    term: "Combining uncertainties: raising to a power",
    answer: "Multiply the percentage uncertainty by the power.",
    detail: "If y = aⁿ then Δy/y = n × (Δa/a). For y = a³ with 2% uncertainty in a, y has 6% uncertainty." },
  { id: "units-23", topic: "units", type: "definition", difficulty: 2,
    term: "Estimating an order of magnitude",
    answer: "Quoting a value to the nearest power of ten.",
    detail: "Useful checks: human height ≈ 10⁰ m, mass of a person ≈ 10² kg, atmospheric pressure ≈ 10⁵ Pa, atomic diameter ≈ 10⁻¹⁰ m." },

  /* ---------- 2. Kinematics ---------- */
  { id: "kin-01", topic: "kin", type: "definition", difficulty: 1,
    term: "Displacement",
    answer: "The distance moved in a stated direction from a fixed point.",
    detail: "A vector. Distance is the scalar equivalent — the total path length travelled." },
  { id: "kin-02", topic: "kin", type: "definition", difficulty: 1,
    term: "Speed",
    answer: "The rate of change of distance travelled.",
    detail: "Scalar. Average speed = total distance / total time." },
  { id: "kin-03", topic: "kin", type: "definition", difficulty: 1,
    term: "Velocity",
    answer: "The rate of change of displacement.",
    detail: "Vector: v = Δs/Δt in a stated direction." },
  { id: "kin-04", topic: "kin", type: "definition", difficulty: 1,
    term: "Acceleration",
    answer: "The rate of change of velocity.",
    detail: "Vector: a = Δv/Δt, unit m s⁻². A change in direction alone is still an acceleration." },
  { id: "kin-05", topic: "kin", type: "formula", difficulty: 1,
    term: "Equation of motion (no displacement)",
    asks: "Give the equation of motion linking v, u, a and t",
    answer: "v = u + at",
    detail: "Comes straight from the definition of acceleration. Valid only for uniform acceleration." },
  { id: "kin-06", topic: "kin", type: "formula", difficulty: 2,
    term: "Equation of motion (no acceleration)",
    asks: "Give the equation of motion linking s, u, v and t",
    answer: "s = (u + v)t / 2",
    detail: "Average velocity × time — this is the area of the trapezium under a velocity-time graph." },
  { id: "kin-07", topic: "kin", type: "formula", difficulty: 2,
    term: "Equation of motion (no final velocity)",
    asks: "Give the equation of motion linking s, u, a and t",
    answer: "s = ut + ½at²",
    detail: "The ut term is the area of the rectangle, ½at² the area of the triangle under a v-t graph." },
  { id: "kin-08", topic: "kin", type: "formula", difficulty: 2,
    term: "Equation of motion (no time)",
    asks: "Give the equation of motion linking v, u, a and s",
    answer: "v² = u² + 2as",
    detail: "Obtained by eliminating t from v = u + at and s = (u+v)t/2. Use it when t is unknown." },
  { id: "kin-09", topic: "kin", type: "theorem", difficulty: 2,
    term: "Gradient of a displacement-time graph",
    asks: "Name the quantity",
    answer: "Velocity",
    graph: "st-gradient",
    detail: "A curved graph means changing velocity — take the gradient of the tangent at that instant." },
  { id: "kin-10", topic: "kin", type: "theorem", difficulty: 2,
    term: "Gradient of a velocity-time graph",
    asks: "Name the quantity",
    answer: "Acceleration",
    graph: "vt-gradient",
    detail: "A negative gradient means deceleration (or acceleration in the negative direction)." },
  { id: "kin-11", topic: "kin", type: "theorem", difficulty: 2,
    term: "Area under a velocity-time graph",
    asks: "Name the quantity",
    answer: "Displacement",
    graph: "vt-area",
    detail: "Area below the time axis counts as negative displacement." },
  { id: "kin-12", topic: "kin", type: "theorem", difficulty: 2,
    term: "Area under an acceleration-time graph",
    asks: "Name the quantity",
    answer: "Change in velocity",
    graph: "at-area",
    detail: "Because a = Δv/Δt, so Δv = a × Δt = area." },
  { id: "kin-13", topic: "kin", type: "definition", difficulty: 1,
    term: "Free fall",
    answer: "Motion under the action of gravitational force alone, with no air resistance.",
    detail: "All objects in free fall have the same acceleration g, independent of mass." },
  { id: "kin-14", topic: "kin", type: "unit", difficulty: 1,
    term: "Acceleration of free fall near the Earth",
    asks: "Give the value, with direction",
    answer: "g = 9.81 m s⁻² (downwards)",
    detail: "Numerically equal to the gravitational field strength, 9.81 N kg⁻¹." },
  { id: "kin-15", topic: "kin", type: "theorem", difficulty: 2,
    term: "Key principle of projectile motion",
    answer: "The horizontal and vertical motions are independent of each other.",
    detail: "Horizontal: constant velocity. Vertical: constant acceleration g. Time is the quantity that links them." },
  { id: "kin-16", topic: "kin", type: "formula", difficulty: 2,
    term: "Projectile: horizontal motion",
    asks: "Give the formula for the horizontal displacement",
    answer: "x = u cosθ × t   (aₓ = 0)",
    detail: "Ignoring air resistance the horizontal velocity component never changes." },
  { id: "kin-17", topic: "kin", type: "formula", difficulty: 2,
    term: "Projectile: vertical motion",
    asks: "Give the formula for the vertical displacement",
    answer: "y = u sinθ × t − ½gt²",
    detail: "Take upwards as positive; the vertical velocity is zero at maximum height." },
  { id: "kin-18", topic: "kin", type: "formula", difficulty: 3,
    term: "Time of flight for a projectile on level ground",
    asks: "Give the formula in terms of u, θ and g",
    answer: "t = 2u sinθ / g",
    detail: "Twice the time to reach the top, since the path is symmetrical when air resistance is ignored." },
  { id: "kin-19", topic: "kin", type: "definition", difficulty: 2,
    term: "Terminal velocity",
    answer: "The constant maximum velocity reached when the drag force equals the weight, so the resultant force and acceleration are zero.",
    graph: "vt-terminal",
    detail: "Drag increases with speed, so acceleration decreases until it reaches zero." },
  { id: "kin-20", topic: "kin", type: "theorem", difficulty: 2,
    term: "Effect of air resistance on a projectile",
    answer: "Range and maximum height are reduced and the path becomes asymmetrical, with a steeper descent.",
    detail: "Drag acts opposite to the velocity, so it removes horizontal velocity throughout the flight." },
  { id: "kin-21", topic: "kin", type: "theorem", difficulty: 1,
    term: "When can suvat equations be used?",
    answer: "Only when the acceleration is constant in magnitude and direction.",
    detail: "For non-uniform acceleration you must use graphs or calculus instead." },

  /* ---------- 3. Dynamics ---------- */
  { id: "dyn-01", topic: "dyn", type: "theorem", difficulty: 1,
    term: "Newton's first law",
    answer: "A body remains at rest or continues to move with constant velocity unless acted on by a resultant external force.",
    detail: "Defines inertia — mass is the measure of a body's resistance to a change in motion." },
  { id: "dyn-02", topic: "dyn", type: "theorem", difficulty: 2,
    term: "Newton's second law",
    answer: "The resultant force is proportional to the rate of change of momentum, and acts in the same direction as that change.",
    detail: "F = Δp/Δt, which reduces to F = ma when the mass is constant." },
  { id: "dyn-03", topic: "dyn", type: "theorem", difficulty: 2,
    term: "Newton's third law",
    answer: "If body A exerts a force on body B, then B exerts an equal and opposite force of the same type on A.",
    detail: "The pair acts on different bodies, so it never cancels out on a single free-body diagram." },
  { id: "dyn-04", topic: "dyn", type: "definition", difficulty: 1,
    term: "Linear momentum",
    answer: "The product of an object's mass and its velocity:  p = mv",
    detail: "A vector, unit kg m s⁻¹ (equivalently N s)." },
  { id: "dyn-05", topic: "dyn", type: "definition", difficulty: 2,
    term: "Impulse",
    answer: "The product of a force and the time for which it acts:  impulse = F × Δt",
    detail: "A vector, unit N s. Equal to the change of momentum it produces." },
  { id: "dyn-06", topic: "dyn", type: "formula", difficulty: 2,
    term: "Impulse-momentum relation",
    asks: "Give the formula linking impulse and change of momentum",
    answer: "FΔt = Δp = mv − mu",
    detail: "Explains crumple zones: increasing Δt for the same Δp reduces the force." },
  { id: "dyn-07", topic: "dyn", type: "theorem", difficulty: 2,
    term: "Principle of conservation of momentum",
    answer: "For a system of interacting bodies, the total momentum in a given direction stays constant provided no resultant external force acts.",
    detail: "Follows from Newton's third law plus the second law. Applies to all collisions and explosions." },
  { id: "dyn-08", topic: "dyn", type: "definition", difficulty: 2,
    term: "Perfectly elastic collision",
    answer: "A collision in which both momentum and total kinetic energy are conserved.",
    detail: "Test: relative speed of approach = relative speed of separation." },
  { id: "dyn-09", topic: "dyn", type: "definition", difficulty: 2,
    term: "Inelastic collision",
    answer: "A collision in which momentum is conserved but total kinetic energy is not.",
    detail: "Kinetic energy becomes internal energy and sound. A perfectly inelastic collision leaves the bodies stuck together." },
  { id: "dyn-10", topic: "dyn", type: "formula", difficulty: 3,
    term: "Elastic collision test",
    asks: "State the test as an equation",
    answer: "u₁ − u₂ = v₂ − v₁",
    detail: "Relative speed of approach equals relative speed of separation — true only for perfectly elastic collisions." },
  { id: "dyn-11", topic: "dyn", type: "formula", difficulty: 2,
    term: "Momentum conservation in a 1-D collision",
    asks: "Give the formula for two bodies colliding in a straight line",
    answer: "m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂",
    detail: "Assign a positive direction first — velocities in the opposite direction go in as negative numbers." },
  { id: "dyn-12", topic: "dyn", type: "unit", difficulty: 1,
    term: "The newton (definition)",
    asks: "Define the unit",
    answer: "The force that gives a mass of 1 kg an acceleration of 1 m s⁻².",
    detail: "So 1 N = 1 kg m s⁻²." },
  { id: "dyn-13", topic: "dyn", type: "formula", difficulty: 1,
    term: "Weight",
    asks: "Give the formula in terms of mass and g",
    answer: "W = mg",
    detail: "The gravitational force on a mass; g is the gravitational field strength in N kg⁻¹." },
  { id: "dyn-14", topic: "dyn", type: "definition", difficulty: 1,
    term: "Mass compared with weight",
    answer: "Mass is the scalar amount of matter (kg) and is constant; weight is the gravitational force on it (N) and varies with g.",
    detail: "Mass also measures inertia — the resistance to acceleration." },
  { id: "dyn-15", topic: "dyn", type: "theorem", difficulty: 2,
    term: "Area under a force-time graph",
    asks: "Name the quantity",
    answer: "Impulse, which equals the change in momentum",
    graph: "ft-area",
    detail: "Useful when the force varies during a collision." },
  { id: "dyn-16", topic: "dyn", type: "theorem", difficulty: 2,
    term: "Momentum in an explosion",
    answer: "Total momentum stays zero: the fragments carry equal and opposite momenta.",
    detail: "Kinetic energy is not conserved — it is created from stored chemical or elastic energy." },
  { id: "dyn-17", topic: "dyn", type: "formula", difficulty: 3,
    term: "Newton's second law for varying mass",
    asks: "Give the rate-of-change-of-momentum form",
    answer: "F = Δ(mv)/Δt",
    detail: "Needed for problems such as water jets or sand falling onto a conveyor, where F = (Δm/Δt)v." },
  { id: "dyn-18", topic: "dyn", type: "theorem", difficulty: 2,
    term: "Condition for equilibrium of a body",
    answer: "The resultant force is zero and the resultant moment about any point is zero.",
    detail: "A body in equilibrium is either stationary or moving with constant velocity." },

  /* ---------- 4. Forces, Density & Pressure ---------- */
  { id: "frc-01", topic: "frc", type: "definition", difficulty: 1,
    term: "Density",
    answer: "Mass per unit volume:  ρ = m / V",
    detail: "Unit kg m⁻³. Water is 1000 kg m⁻³ (1.0 g cm⁻³)." },
  { id: "frc-02", topic: "frc", type: "definition", difficulty: 1,
    term: "Pressure",
    answer: "Force acting normally per unit area:  p = F / A",
    detail: "Scalar, unit pascal (Pa) = N m⁻². The force must be perpendicular to the surface." },
  { id: "frc-03", topic: "frc", type: "formula", difficulty: 2,
    term: "Pressure due to a column of fluid",
    asks: "Give the formula in terms of density, g and depth",
    answer: "Δp = ρgΔh",
    detail: "Depends only on depth and density, not on the shape or cross-section of the container." },
  { id: "frc-04", topic: "frc", type: "theorem", difficulty: 2,
    term: "Origin of upthrust (Archimedes' principle)",
    answer: "Upthrust equals the weight of the fluid displaced:  F = ρgV",
    detail: "It arises because fluid pressure increases with depth, so the upward force on the base exceeds the downward force on the top." },
  { id: "frc-05", topic: "frc", type: "definition", difficulty: 2,
    term: "Moment of a force",
    answer: "The product of the force and the perpendicular distance of its line of action from the pivot.",
    detail: "Moment = F × d, unit N m. A vector-like quantity described as clockwise or anticlockwise." },
  { id: "frc-06", topic: "frc", type: "definition", difficulty: 2,
    term: "Couple",
    answer: "A pair of equal and opposite forces whose lines of action do not coincide.",
    detail: "A couple produces rotation only — the resultant force on the body is zero." },
  { id: "frc-07", topic: "frc", type: "formula", difficulty: 2,
    term: "Torque of a couple",
    asks: "Give the formula in terms of one force and their separation",
    answer: "T = F × d",
    detail: "F is one of the forces and d the perpendicular separation of their lines of action. The torque is the same about every point." },
  { id: "frc-08", topic: "frc", type: "theorem", difficulty: 2,
    term: "Principle of moments",
    answer: "For a body in equilibrium, the sum of clockwise moments about any point equals the sum of anticlockwise moments about that point.",
    detail: "Choose the pivot through an unknown force to eliminate it from the equation." },
  { id: "frc-09", topic: "frc", type: "definition", difficulty: 2,
    term: "Centre of gravity",
    answer: "The single point at which the entire weight of a body may be considered to act.",
    detail: "For a uniform body in a uniform field it coincides with the geometric centre." },
  { id: "frc-10", topic: "frc", type: "theorem", difficulty: 2,
    term: "Closed-triangle rule for three forces",
    answer: "If three coplanar forces keep a body in equilibrium, their vector diagram forms a closed triangle and their lines of action meet at a point.",
    detail: "Useful for scale-drawing solutions to equilibrium problems." },
  { id: "frc-11", topic: "frc", type: "formula", difficulty: 2,
    term: "Forces on an object on a smooth incline",
    asks: "Give both the component along the slope and the normal contact force",
    answer: "Along slope: mg sinθ.  Perpendicular: N = mg cosθ",
    detail: "Resolve the weight parallel and perpendicular to the surface, not vertically and horizontally." },
  { id: "frc-12", topic: "frc", type: "definition", difficulty: 1,
    term: "Normal contact force",
    answer: "The force exerted by a surface on a body, acting perpendicular to that surface.",
    detail: "Its Newton's-third-law pair is the force the body exerts on the surface." },
  { id: "frc-13", topic: "frc", type: "definition", difficulty: 2,
    term: "Frictional force",
    answer: "A contact force opposing relative motion (or attempted motion) between two surfaces.",
    detail: "It converts kinetic energy into internal energy, raising the temperature of the surfaces." },
  { id: "frc-14", topic: "frc", type: "definition", difficulty: 2,
    term: "Viscous drag",
    answer: "The resistive force on a body moving through a fluid, which increases with speed.",
    detail: "Together with weight and upthrust it determines the terminal velocity of a falling sphere." },
  { id: "frc-15", topic: "frc", type: "unit", difficulty: 1,
    term: "The pascal",
    asks: "Express in N m⁻² and in SI base units",
    answer: "1 Pa = 1 N m⁻² = 1 kg m⁻¹ s⁻²",
    detail: "Atmospheric pressure is about 1.0 × 10⁵ Pa." },
  { id: "frc-16", topic: "frc", type: "theorem", difficulty: 2,
    term: "Condition for a body to float",
    answer: "Upthrust equals weight, so the body displaces a weight of fluid equal to its own weight.",
    detail: "It follows that a body floats when its average density is less than that of the fluid." },

  /* ---------- 5. Work, Energy & Power ---------- */
  { id: "nrg-01", topic: "nrg", type: "definition", difficulty: 1,
    term: "Work done",
    answer: "The product of the force and the distance moved in the direction of the force.",
    detail: "W = Fs cosθ, unit joule. No work is done if the displacement is perpendicular to the force." },
  { id: "nrg-02", topic: "nrg", type: "formula", difficulty: 1,
    term: "Work done by a force at an angle",
    asks: "Give the formula including the angle between force and displacement",
    answer: "W = Fs cosθ",
    detail: "θ is the angle between the force and the displacement. cos 90° = 0, so a centripetal force does no work." },
  { id: "nrg-03", topic: "nrg", type: "unit", difficulty: 1,
    term: "The joule",
    asks: "Define the unit",
    answer: "The work done when a force of 1 N moves its point of application 1 m in the direction of the force.",
    detail: "1 J = 1 N m = 1 kg m² s⁻²." },
  { id: "nrg-04", topic: "nrg", type: "formula", difficulty: 1,
    term: "Kinetic energy",
    asks: "Give the formula in terms of mass and speed",
    answer: "Eₖ = ½mv²",
    detail: "Derived from W = Fs with F = ma and v² = u² + 2as starting from rest." },
  { id: "nrg-05", topic: "nrg", type: "formula", difficulty: 1,
    term: "Change in gravitational potential energy",
    asks: "Give the formula in terms of mass, g and height",
    answer: "ΔE_p = mgΔh",
    detail: "Valid near the Earth's surface where g is effectively uniform; Δh is the vertical height change." },
  { id: "nrg-06", topic: "nrg", type: "theorem", difficulty: 1,
    term: "Principle of conservation of energy",
    answer: "Energy cannot be created or destroyed; it can only be transferred from one form to another, and the total energy of an isolated system is constant.",
    detail: "The book-keeping rule behind every energy calculation." },
  { id: "nrg-07", topic: "nrg", type: "definition", difficulty: 1,
    term: "Power",
    answer: "The rate of doing work, or the rate of energy transfer.",
    detail: "P = W/t, unit watt (W) = J s⁻¹." },
  { id: "nrg-08", topic: "nrg", type: "formula", difficulty: 2,
    term: "Power of a force moving at constant velocity",
    asks: "Give the formula in terms of force and velocity",
    answer: "P = Fv",
    detail: "From P = W/t = Fs/t. Used for vehicles moving at steady speed against a resistive force." },
  { id: "nrg-09", topic: "nrg", type: "formula", difficulty: 1,
    term: "Efficiency",
    asks: "Give the formula as a percentage",
    answer: "efficiency = (useful energy output / total energy input) × 100%",
    detail: "Equivalently useful power out / total power in. Never exceeds 100%." },
  { id: "nrg-10", topic: "nrg", type: "unit", difficulty: 1,
    term: "The watt",
    asks: "Define the unit",
    answer: "The rate of energy transfer of 1 joule per second.",
    detail: "1 W = 1 J s⁻¹ = 1 kg m² s⁻³." },
  { id: "nrg-11", topic: "nrg", type: "formula", difficulty: 3,
    term: "Work done by an expanding gas",
    asks: "Give the formula for constant pressure",
    answer: "W = pΔV",
    graph: "pv-work",
    detail: "Valid at constant pressure; it is the area under a pressure-volume graph." },
  { id: "nrg-12", topic: "nrg", type: "theorem", difficulty: 2,
    term: "Derivation of Eₖ = ½mv²",
    answer: "W = Fs = (ma)s and v² = 0 + 2as gives s = v²/2a, so W = ma × v²/2a = ½mv².",
    detail: "The work done accelerating a mass from rest equals its kinetic energy." },
  { id: "nrg-13", topic: "nrg", type: "theorem", difficulty: 2,
    term: "Energy in a falling object (no air resistance)",
    answer: "Loss in gravitational potential energy = gain in kinetic energy:  mgh = ½mv²",
    detail: "Rearranging gives v = √(2gh) — independent of mass." },
  { id: "nrg-14", topic: "nrg", type: "theorem", difficulty: 2,
    term: "Energy when friction is present",
    answer: "Work done against friction = loss in total mechanical energy, appearing as internal energy.",
    detail: "So ½mv² + mgh is no longer constant — the difference heats the surfaces." },
  { id: "nrg-15", topic: "nrg", type: "theorem", difficulty: 2,
    term: "Area under a force-distance graph",
    asks: "Name the quantity",
    answer: "Work done by the force",
    graph: "fx-work",
    detail: "Used when force varies, e.g. stretching a spring where the area is ½Fx." },

  /* ---------- 6. Deformation of Solids ---------- */
  { id: "def-01", topic: "def", type: "theorem", difficulty: 1,
    term: "Hooke's law",
    answer: "The extension of a body is proportional to the applied force, provided the limit of proportionality is not exceeded.",
    graph: "hooke",
    detail: "F = kx, where k is the force constant." },
  { id: "def-02", topic: "def", type: "definition", difficulty: 1,
    term: "Spring (force) constant k",
    answer: "The force per unit extension:  k = F / x",
    graph: "hooke",
    detail: "Unit N m⁻¹; it is the gradient of the straight-line region of a force-extension graph." },
  { id: "def-03", topic: "def", type: "definition", difficulty: 2,
    term: "Limit of proportionality",
    answer: "The point beyond which extension is no longer proportional to the applied force.",
    graph: "fx-limit",
    detail: "The force-extension graph stops being a straight line here." },
  { id: "def-04", topic: "def", type: "definition", difficulty: 2,
    term: "Elastic limit",
    answer: "The maximum force beyond which the body no longer returns to its original length when the load is removed.",
    detail: "Just past the limit of proportionality; beyond it the deformation is plastic." },
  { id: "def-05", topic: "def", type: "definition", difficulty: 1,
    term: "Elastic deformation",
    answer: "Deformation from which the body returns to its original shape and size when the load is removed.",
    detail: "All the work done is stored as elastic potential energy and is recoverable." },
  { id: "def-06", topic: "def", type: "definition", difficulty: 1,
    term: "Plastic deformation",
    answer: "Deformation in which the body does not return to its original shape and size when the load is removed.",
    detail: "A permanent extension remains; energy has been used to move layers of atoms past each other." },
  { id: "def-07", topic: "def", type: "definition", difficulty: 2,
    term: "Tensile stress",
    answer: "Force applied per unit cross-sectional area:  σ = F / A",
    detail: "Unit pascal (Pa) or N m⁻², the same as pressure." },
  { id: "def-08", topic: "def", type: "definition", difficulty: 2,
    term: "Tensile strain",
    answer: "Extension per unit original length:  ε = x / L",
    detail: "A ratio, so it has no units. Often quoted as a percentage." },
  { id: "def-09", topic: "def", type: "definition", difficulty: 2,
    term: "Young modulus",
    answer: "The ratio of tensile stress to tensile strain:  E = σ / ε = FL / Ax",
    graph: "stress-strain",
    detail: "Unit Pa. A material constant valid below the limit of proportionality; it is the gradient of the linear part of a stress-strain graph." },
  { id: "def-10", topic: "def", type: "formula", difficulty: 2,
    term: "Elastic potential energy in a spring",
    asks: "Give it in terms of force, and in terms of the spring constant",
    answer: "E = ½Fx = ½kx²",
    graph: "fx-strain-energy",
    detail: "Equal to the area under the force-extension graph, valid within the limit of proportionality." },
  { id: "def-11", topic: "def", type: "theorem", difficulty: 2,
    term: "Area under a force-extension graph",
    asks: "Name the quantity",
    answer: "The work done in stretching, i.e. the strain energy stored",
    graph: "fx-strain-energy",
    detail: "If the material has deformed plastically, the area between loading and unloading curves is energy lost as internal energy." },
  { id: "def-12", topic: "def", type: "definition", difficulty: 2,
    term: "Ultimate tensile stress",
    answer: "The maximum stress a material can withstand before it breaks.",
    graph: "stress-uts",
    detail: "The peak of the stress-strain graph, sometimes called the breaking stress." },
  { id: "def-13", topic: "def", type: "formula", difficulty: 3,
    term: "Springs in series and in parallel",
    asks: "Give the formula for both arrangements",
    answer: "Series: 1/k_total = 1/k₁ + 1/k₂.  Parallel: k_total = k₁ + k₂",
    detail: "Springs in series share the same force and extensions add; in parallel they share the load and have equal extension." },
  { id: "def-14", topic: "def", type: "definition", difficulty: 2,
    term: "Compressive versus tensile force",
    answer: "A tensile force stretches a body; a compressive force squashes it.",
    detail: "A pair of equal and opposite forces is needed in both cases, otherwise the body accelerates instead of deforming." },
  { id: "def-15", topic: "def", type: "theorem", difficulty: 2,
    term: "Why stress-strain graphs are preferred to force-extension graphs",
    answer: "Stress and strain depend only on the material, not on the sample's dimensions.",
    detail: "So a stress-strain graph lets different samples of the same material be compared directly." },

  /* ---------- 7. Waves ---------- */
  { id: "wav-01", topic: "wav", type: "definition", difficulty: 1,
    term: "Progressive wave",
    answer: "A wave that transfers energy from one point to another without any net transfer of the medium itself.",
    detail: "Particles oscillate about fixed equilibrium positions." },
  { id: "wav-02", topic: "wav", type: "definition", difficulty: 1,
    term: "Displacement (wave)",
    answer: "The distance of a particle from its equilibrium position, in a stated direction.",
    detail: "A vector — it can be positive or negative." },
  { id: "wav-03", topic: "wav", type: "definition", difficulty: 1,
    term: "Amplitude",
    answer: "The maximum displacement of a particle from its equilibrium position.",
    detail: "Intensity is proportional to amplitude squared." },
  { id: "wav-04", topic: "wav", type: "definition", difficulty: 1,
    term: "Period",
    answer: "The time taken for one complete oscillation of a particle in the wave.",
    detail: "T = 1/f, unit second." },
  { id: "wav-05", topic: "wav", type: "definition", difficulty: 1,
    term: "Frequency",
    answer: "The number of complete oscillations per unit time at a point in the wave.",
    detail: "f = 1/T, unit hertz (Hz) = s⁻¹." },
  { id: "wav-06", topic: "wav", type: "definition", difficulty: 1,
    term: "Wavelength",
    answer: "The distance between two adjacent points on a wave that are in phase.",
    detail: "For example crest to crest, or compression to compression." },
  { id: "wav-07", topic: "wav", type: "formula", difficulty: 1,
    term: "Wave equation",
    asks: "Give the formula linking speed, frequency and wavelength",
    answer: "v = fλ",
    detail: "Follows from speed = distance/time: one wavelength travels past in one period, so v = λ/T = fλ." },
  { id: "wav-08", topic: "wav", type: "definition", difficulty: 2,
    term: "Phase difference",
    answer: "The fraction of a cycle by which one oscillation leads or lags another, expressed as an angle.",
    detail: "Phase difference = (path difference / λ) × 360°, or × 2π radians." },
  { id: "wav-09", topic: "wav", type: "definition", difficulty: 1,
    term: "Transverse wave",
    answer: "A wave in which the oscillations are perpendicular to the direction of energy transfer.",
    detail: "Examples: all electromagnetic waves, water waves, waves on a string. Only transverse waves can be polarised." },
  { id: "wav-10", topic: "wav", type: "definition", difficulty: 1,
    term: "Longitudinal wave",
    answer: "A wave in which the oscillations are parallel to the direction of energy transfer.",
    detail: "Example: sound. Consists of compressions and rarefactions and cannot be polarised." },
  { id: "wav-11", topic: "wav", type: "definition", difficulty: 2,
    term: "Intensity",
    answer: "The power transmitted per unit area normal to the direction of wave travel:  I = P / A",
    detail: "Unit W m⁻²." },
  { id: "wav-12", topic: "wav", type: "theorem", difficulty: 2,
    term: "Intensity and amplitude",
    asks: "State the relationship as a proportionality",
    answer: "I ∝ A²",
    detail: "Doubling the amplitude quadruples the intensity." },
  { id: "wav-13", topic: "wav", type: "theorem", difficulty: 2,
    term: "Intensity from a point source",
    asks: "State the relationship as a proportionality",
    answer: "I ∝ 1/r²  (inverse square law)",
    detail: "The same power spreads over a sphere of area 4πr²." },
  { id: "wav-14", topic: "wav", type: "formula", difficulty: 3,
    term: "Doppler effect for a moving source",
    asks: "Give the formula for the observed frequency",
    answer: "f_o = f_s v / (v ± v_s)",
    detail: "Minus when the source approaches (higher observed frequency), plus when it recedes. v is the wave speed." },
  { id: "wav-15", topic: "wav", type: "definition", difficulty: 2,
    term: "Order of the electromagnetic spectrum",
    answer: "radio, microwave, infrared, visible, ultraviolet, X-ray, gamma  (increasing frequency)",
    detail: "Wavelength decreases and photon energy increases along that order." },
  { id: "wav-16", topic: "wav", type: "unit", difficulty: 1,
    term: "Speed of electromagnetic waves in a vacuum",
    asks: "Give the value",
    answer: "c = 3.0 × 10⁸ m s⁻¹",
    detail: "The same for all EM waves in free space, whatever their frequency." },
  { id: "wav-17", topic: "wav", type: "unit", difficulty: 2,
    term: "Wavelength range of visible light",
    asks: "Give the range in nm",
    answer: "About 400 nm (violet) to 700 nm (red)",
    detail: "That is 4 × 10⁻⁷ m to 7 × 10⁻⁷ m." },
  { id: "wav-18", topic: "wav", type: "definition", difficulty: 2,
    term: "Polarisation",
    answer: "The restriction of the oscillations of a transverse wave to a single plane containing the direction of travel.",
    detail: "Only possible for transverse waves, which is evidence that light is transverse." },
  { id: "wav-19", topic: "wav", type: "formula", difficulty: 3,
    term: "Malus's law",
    asks: "Give the formula for the transmitted intensity",
    answer: "I = I₀ cos²θ",
    detail: "Intensity transmitted by an analyser at angle θ to the plane of polarisation of light of intensity I₀." },
  { id: "wav-20", topic: "wav", type: "definition", difficulty: 2,
    term: "Wavefront",
    answer: "A line or surface joining points of a wave that are all in phase.",
    detail: "Wavefronts are one wavelength apart and always perpendicular to the direction of travel." },
  { id: "wav-21", topic: "wav", type: "theorem", difficulty: 2,
    term: "Using a cathode-ray oscilloscope to find frequency",
    answer: "T = (number of horizontal divisions for one cycle) × (time-base setting), then f = 1/T",
    detail: "The y-gain setting converts vertical divisions into voltage." },

  /* ---------- 8. Superposition ---------- */
  { id: "sup-01", topic: "sup", type: "theorem", difficulty: 1,
    term: "Principle of superposition",
    answer: "When two or more waves meet at a point, the resultant displacement is the vector sum of the individual displacements.",
    detail: "The waves pass through each other unchanged after overlapping." },
  { id: "sup-02", topic: "sup", type: "definition", difficulty: 1,
    term: "Interference",
    answer: "The superposition of two or more waves producing a resultant with a pattern of reinforcement and cancellation.",
    detail: "Constructive where the waves arrive in phase, destructive where they arrive in antiphase." },
  { id: "sup-03", topic: "sup", type: "definition", difficulty: 2,
    term: "Coherence",
    answer: "Two sources are coherent if they have a constant phase difference (and therefore the same frequency).",
    detail: "Required for a stable, observable interference pattern." },
  { id: "sup-04", topic: "sup", type: "theorem", difficulty: 2,
    term: "Path difference condition for constructive interference",
    asks: "Give the condition as a path difference",
    answer: "Path difference = nλ  (n = 0, 1, 2, …)",
    detail: "A whole number of wavelengths means the waves arrive in phase." },
  { id: "sup-05", topic: "sup", type: "theorem", difficulty: 2,
    term: "Path difference condition for destructive interference",
    asks: "Give the condition as a path difference",
    answer: "Path difference = (n + ½)λ",
    detail: "An odd number of half-wavelengths means the waves arrive in antiphase and cancel." },
  { id: "sup-06", topic: "sup", type: "theorem", difficulty: 2,
    term: "Conditions for observable two-source interference",
    answer: "Coherent sources of the same type, similar amplitude, and (for light) the same polarisation, overlapping in the same region.",
    detail: "Equal amplitudes give complete cancellation at the minima and so the highest contrast." },
  { id: "sup-07", topic: "sup", type: "formula", difficulty: 2,
    term: "Young double-slit formula",
    asks: "Give the formula in terms of fringe separation, slit separation and screen distance",
    answer: "λ = ax / D",
    detail: "a = slit separation, x = fringe separation, D = slit-to-screen distance. Valid when D is much greater than a." },
  { id: "sup-08", topic: "sup", type: "definition", difficulty: 2,
    term: "Diffraction",
    answer: "The spreading of a wave as it passes through a gap or around an obstacle.",
    detail: "Most pronounced when the gap width is comparable to the wavelength." },
  { id: "sup-09", topic: "sup", type: "formula", difficulty: 2,
    term: "Diffraction grating equation",
    asks: "Give the formula in terms of d, θ, n and λ",
    answer: "d sinθ = nλ",
    detail: "d = slit spacing, θ = angle of the nth order maximum from the normal, n = order number." },
  { id: "sup-10", topic: "sup", type: "formula", difficulty: 2,
    term: "Slit spacing of a diffraction grating",
    asks: "Give the formula in terms of the number of lines per metre",
    answer: "d = 1 / N",
    detail: "N is the number of lines per metre. For 600 lines/mm, d = 1/(6.00 × 10⁵) m." },
  { id: "sup-11", topic: "sup", type: "theorem", difficulty: 2,
    term: "Why a grating gives sharper maxima than two slits",
    answer: "Many slits give sharper, brighter maxima because waves from all slits reinforce only at precise angles and cancel elsewhere.",
    detail: "This makes a grating far more accurate for measuring wavelength." },
  { id: "sup-12", topic: "sup", type: "definition", difficulty: 2,
    term: "Stationary (standing) wave",
    answer: "A wave formed by the superposition of two progressive waves of the same frequency and amplitude travelling in opposite directions.",
    detail: "Usually produced by reflecting a wave back along its own path. It stores energy rather than transferring it." },
  { id: "sup-13", topic: "sup", type: "definition", difficulty: 1,
    term: "Node",
    answer: "A point on a stationary wave where the amplitude is always zero.",
    graph: "stationary-wave",
    detail: "Formed where the two waves are permanently in antiphase." },
  { id: "sup-14", topic: "sup", type: "definition", difficulty: 1,
    term: "Antinode",
    answer: "A point on a stationary wave where the amplitude is a maximum.",
    graph: "stationary-wave",
    detail: "Formed where the two waves are permanently in phase." },
  { id: "sup-15", topic: "sup", type: "theorem", difficulty: 2,
    term: "Separation of adjacent nodes",
    answer: "λ / 2",
    graph: "stationary-wave",
    detail: "A node and its neighbouring antinode are λ/4 apart — this is how a stationary wave is used to measure wavelength." },
  { id: "sup-16", topic: "sup", type: "theorem", difficulty: 3,
    term: "Stationary wave versus progressive wave",
    answer: "A stationary wave transfers no energy, has fixed nodes and antinodes, amplitude varies with position, and points between nodes are in phase.",
    detail: "In a progressive wave energy is transferred, every particle has the same amplitude, and phase varies continuously with position." },
  { id: "sup-17", topic: "sup", type: "formula", difficulty: 3,
    term: "Fundamental frequency of a stretched string",
    asks: "Give the fundamental wavelength and frequency",
    answer: "λ = 2L, so f = v / 2L",
    graph: "string-fundamental",
    detail: "The fundamental has a node at each end and one antinode in the middle. Harmonics are integer multiples of f." },
  { id: "sup-18", topic: "sup", type: "formula", difficulty: 3,
    term: "Fundamental of a pipe closed at one end",
    asks: "Give the fundamental wavelength and frequency",
    answer: "λ = 4L, so f = v / 4L",
    graph: "pipe-closed",
    detail: "Node at the closed end, antinode at the open end. Only odd harmonics are possible." },
  { id: "sup-19", topic: "sup", type: "theorem", difficulty: 2,
    term: "Measuring the wavelength of microwaves",
    answer: "Reflect the beam from a metal plate to form a stationary wave, then move a probe to find the node spacing, which is λ/2.",
    detail: "The same node-spacing method is used with sound in a resonance tube." },

  /* ---------- 9. Electricity ---------- */
  { id: "ele-01", topic: "ele", type: "definition", difficulty: 1,
    term: "Electric current",
    answer: "The rate of flow of charge:  I = ΔQ / Δt",
    detail: "Unit ampere (A). Conventional current flows from positive to negative, opposite to electron flow." },
  { id: "ele-02", topic: "ele", type: "unit", difficulty: 1,
    term: "The coulomb",
    asks: "Define the unit",
    answer: "The charge that passes a point when a current of 1 A flows for 1 s.",
    detail: "1 C = 1 A s." },
  { id: "ele-03", topic: "ele", type: "formula", difficulty: 1,
    term: "Charge transferred",
    asks: "Give the formula in terms of current and time",
    answer: "Q = It",
    detail: "For a varying current, Q is the area under the current-time graph." },
  { id: "ele-04", topic: "ele", type: "unit", difficulty: 2,
    term: "Elementary charge",
    asks: "Give the value",
    answer: "e = 1.60 × 10⁻¹⁹ C",
    detail: "Charge is quantised: every observed charge is a whole-number multiple of e." },
  { id: "ele-05", topic: "ele", type: "definition", difficulty: 2,
    term: "Potential difference",
    answer: "The energy transferred from electrical to other forms per unit charge passing between two points.",
    detail: "V = W/Q, unit volt (V) = J C⁻¹." },
  { id: "ele-06", topic: "ele", type: "definition", difficulty: 2,
    term: "Electromotive force (e.m.f.)",
    answer: "The energy transferred from other forms into electrical energy per unit charge driven round a circuit by a source.",
    detail: "Same unit as p.d. — the difference is the direction of the energy conversion." },
  { id: "ele-07", topic: "ele", type: "unit", difficulty: 1,
    term: "The volt",
    asks: "Define the unit",
    answer: "One joule of energy transferred per coulomb of charge.",
    detail: "1 V = 1 J C⁻¹ = 1 kg m² s⁻³ A⁻¹." },
  { id: "ele-08", topic: "ele", type: "definition", difficulty: 1,
    term: "Resistance",
    answer: "The ratio of the potential difference across a component to the current through it:  R = V / I",
    detail: "Unit ohm (Ω). Defined for any component, whether or not it obeys Ohm's law." },
  { id: "ele-09", topic: "ele", type: "theorem", difficulty: 2,
    term: "Ohm's law",
    answer: "The current through a metallic conductor is proportional to the potential difference across it, provided physical conditions such as temperature stay constant.",
    graph: "iv-ohmic",
    detail: "A component obeying it is called ohmic and has a straight-line I-V graph through the origin." },
  { id: "ele-10", topic: "ele", type: "unit", difficulty: 1,
    term: "The ohm",
    asks: "Define the unit",
    answer: "The resistance of a component with a p.d. of 1 V across it when a current of 1 A flows.",
    detail: "1 Ω = 1 V A⁻¹." },
  { id: "ele-11", topic: "ele", type: "formula", difficulty: 3,
    term: "Current in terms of charge carriers",
    asks: "Give the formula in terms of the charge carriers",
    answer: "I = nAvq",
    detail: "n = number density of carriers, A = cross-sectional area, v = mean drift velocity, q = charge per carrier." },
  { id: "ele-12", topic: "ele", type: "definition", difficulty: 2,
    term: "Resistivity",
    asks: "Define it in words and as an equation",
    answer: "Resistance × cross-sectional area / length:  ρ = RA / L",
    detail: "A property of the material, unit Ω m. Resistance increases with length and decreases with cross-sectional area." },
  { id: "ele-13", topic: "ele", type: "formula", difficulty: 1,
    term: "Electrical power",
    asks: "Give the formula in terms of p.d. and current",
    answer: "P = VI",
    detail: "From P = W/t with W = VQ and Q = It." },
  { id: "ele-14", topic: "ele", type: "formula", difficulty: 2,
    term: "Power in terms of resistance",
    asks: "Give both the I²R and the V²/R form",
    answer: "P = I²R = V² / R",
    detail: "Substitute V = IR into P = VI. Use I²R for series problems and V²/R for parallel problems." },
  { id: "ele-15", topic: "ele", type: "formula", difficulty: 2,
    term: "Electrical energy transferred",
    asks: "Give the formula in terms of V, I and t",
    answer: "W = VIt = I²Rt",
    detail: "Unit joule; domestic energy is metered in kilowatt-hours instead." },
  { id: "ele-16", topic: "ele", type: "theorem", difficulty: 2,
    term: "I-V characteristic of a metallic conductor at constant temperature",
    answer: "A straight line through the origin — resistance is constant.",
    graph: "iv-ohmic",
    detail: "It obeys Ohm's law. If the wire heats up the line curves towards the current axis." },
  { id: "ele-17", topic: "ele", type: "theorem", difficulty: 2,
    term: "I-V characteristic of a filament lamp",
    answer: "A curve that bends towards the V axis: resistance increases as the current increases.",
    graph: "iv-lamp",
    detail: "Higher current raises the temperature, so lattice ions vibrate more and impede electron flow." },
  { id: "ele-18", topic: "ele", type: "theorem", difficulty: 2,
    term: "I-V characteristic of a semiconductor diode",
    answer: "Almost no current until the forward threshold voltage (about 0.6 V), then current rises steeply; in reverse bias the resistance is very high.",
    graph: "iv-diode",
    detail: "A diode is non-ohmic and only conducts appreciably in one direction." },
  { id: "ele-19", topic: "ele", type: "definition", difficulty: 2,
    term: "Thermistor (NTC)",
    answer: "A component whose resistance decreases markedly as its temperature increases.",
    graph: "r-temp",
    detail: "More charge carriers are released at higher temperature. Used in temperature-sensing potential dividers." },
  { id: "ele-20", topic: "ele", type: "definition", difficulty: 2,
    term: "Light-dependent resistor (LDR)",
    answer: "A component whose resistance decreases as the light intensity on it increases.",
    graph: "r-light",
    detail: "Used in light-sensing potential-divider circuits." },
  { id: "ele-21", topic: "ele", type: "definition", difficulty: 3,
    term: "Mean drift velocity",
    answer: "The average velocity of the charge carriers along the conductor caused by the applied p.d.",
    detail: "Typically less than 1 mm s⁻¹ in a copper wire, even though the electric field is set up almost instantly." },
  { id: "ele-22", topic: "ele", type: "unit", difficulty: 2,
    term: "The kilowatt-hour",
    asks: "Give the value in joules",
    answer: "1 kW h = 3.6 × 10⁶ J",
    detail: "1000 W × 3600 s. The commercial unit of electrical energy." },

  /* ---------- 10. D.C. Circuits ---------- */
  { id: "dc-01", topic: "dc", type: "theorem", difficulty: 1,
    term: "Kirchhoff's first law",
    answer: "The sum of the currents entering a junction equals the sum of the currents leaving it.",
    detail: "A consequence of the conservation of charge." },
  { id: "dc-02", topic: "dc", type: "theorem", difficulty: 2,
    term: "Kirchhoff's second law",
    answer: "Round any closed loop, the sum of the e.m.f.s equals the sum of the p.d.s.",
    detail: "A consequence of the conservation of energy." },
  { id: "dc-03", topic: "dc", type: "formula", difficulty: 1,
    term: "Resistors in series",
    asks: "Give the formula for n resistors",
    answer: "R = R₁ + R₂ + R₃ + …",
    detail: "Same current through each; the p.d.s add. The total is always larger than the largest individual resistor." },
  { id: "dc-04", topic: "dc", type: "formula", difficulty: 1,
    term: "Resistors in parallel",
    asks: "Give the formula for n resistors",
    answer: "1/R = 1/R₁ + 1/R₂ + 1/R₃ + …",
    detail: "Same p.d. across each; the currents add. The total is always smaller than the smallest individual resistor." },
  { id: "dc-05", topic: "dc", type: "definition", difficulty: 2,
    term: "Internal resistance",
    answer: "The resistance of the source itself, which causes energy to be dissipated inside the source.",
    detail: "It is why the terminal p.d. falls as the current drawn increases." },
  { id: "dc-06", topic: "dc", type: "formula", difficulty: 2,
    term: "E.m.f. with internal resistance",
    asks: "Give the formula linking e.m.f., current, external and internal resistance",
    answer: "E = I(R + r) = V + Ir",
    graph: "emf-internal",
    detail: "A graph of terminal p.d. V against current I has gradient −r and intercept E." },
  { id: "dc-07", topic: "dc", type: "definition", difficulty: 2,
    term: "Terminal potential difference",
    answer: "The p.d. across the external circuit:  V = E − Ir",
    detail: "Equal to the e.m.f. only when no current flows (an open circuit)." },
  { id: "dc-08", topic: "dc", type: "definition", difficulty: 2,
    term: "Lost volts",
    answer: "The p.d. dropped across the internal resistance:  Ir = E − V",
    detail: "This energy per coulomb is dissipated inside the source and warms it." },
  { id: "dc-09", topic: "dc", type: "formula", difficulty: 2,
    term: "Potential divider equation",
    asks: "Give the formula for the output p.d.",
    answer: "V_out = V_in × R₂ / (R₁ + R₂)",
    detail: "R₂ is the resistor across which the output is taken. The p.d. splits in proportion to resistance." },
  { id: "dc-10", topic: "dc", type: "definition", difficulty: 2,
    term: "Potentiometer",
    answer: "A continuously variable potential divider, usually a uniform resistance wire with a sliding contact.",
    detail: "Used to compare e.m.f.s: with a balanced null reading no current is drawn, so internal resistance has no effect." },
  { id: "dc-11", topic: "dc", type: "theorem", difficulty: 2,
    term: "Ideal ammeter and voltmeter resistances",
    answer: "An ideal ammeter has zero resistance; an ideal voltmeter has infinite resistance.",
    detail: "So neither instrument changes the currents or p.d.s it is measuring." },
  { id: "dc-12", topic: "dc", type: "theorem", difficulty: 2,
    term: "Cells in series and in parallel",
    answer: "Series: e.m.f.s add and internal resistances add. Identical cells in parallel: e.m.f. unchanged, internal resistance divided by the number of cells.",
    detail: "Cells connected in opposition subtract their e.m.f.s." },
  { id: "dc-13", topic: "dc", type: "formula", difficulty: 3,
    term: "Efficiency of energy transfer from a cell",
    asks: "Give the formula in terms of R and r",
    answer: "efficiency = R / (R + r) × 100%",
    detail: "Equivalently the ratio of terminal p.d. to e.m.f., V/E." },
  { id: "dc-14", topic: "dc", type: "theorem", difficulty: 2,
    term: "Why a thermistor is used in a potential divider",
    answer: "Its resistance changes with temperature, so the output p.d. of the divider changes and can trigger a control circuit.",
    detail: "The same idea with an LDR gives a light-sensing switch." },
  { id: "dc-15", topic: "dc", type: "theorem", difficulty: 3,
    term: "Balanced potentiometer condition",
    answer: "At balance the galvanometer reads zero, so the e.m.f. of the test cell equals the p.d. across the balance length:  E ∝ l",
    detail: "Comparing two balance lengths gives E₁/E₂ = l₁/l₂." },

  /* ---------- 11. Particle & Nuclear Physics ---------- */
  { id: "nuc-01", topic: "nuc", type: "theorem", difficulty: 2,
    term: "Alpha-particle scattering experiment: observations",
    answer: "Most alpha particles passed straight through, a few were deflected through large angles, and a very small number were reflected back.",
    detail: "Geiger and Marsden fired alpha particles at thin gold foil." },
  { id: "nuc-02", topic: "nuc", type: "theorem", difficulty: 2,
    term: "Alpha-particle scattering: conclusions",
    answer: "The atom is mostly empty space, with nearly all its mass and all its positive charge concentrated in a very small, dense nucleus.",
    detail: "Large-angle deflections require a strong electrostatic repulsion from a concentrated positive charge." },
  { id: "nuc-03", topic: "nuc", type: "definition", difficulty: 1,
    term: "Proton number Z",
    answer: "The number of protons in the nucleus.",
    detail: "Also called the atomic number; it fixes which element the atom is." },
  { id: "nuc-04", topic: "nuc", type: "definition", difficulty: 1,
    term: "Nucleon number A",
    answer: "The total number of protons and neutrons in the nucleus.",
    detail: "Also called the mass number. Number of neutrons = A − Z." },
  { id: "nuc-05", topic: "nuc", type: "definition", difficulty: 1,
    term: "Isotopes",
    answer: "Nuclei of the same element with the same proton number but different numbers of neutrons.",
    detail: "They have identical chemistry but different masses and nuclear stability." },
  { id: "nuc-06", topic: "nuc", type: "definition", difficulty: 2,
    term: "Nuclide notation",
    answer: "ᴬ_Z X — nucleon number above, proton number below the element symbol.",
    detail: "In every nuclear equation both A and Z must balance on the two sides." },
  { id: "nuc-07", topic: "nuc", type: "formula", difficulty: 2,
    term: "Alpha decay",
    asks: "Give the general nuclear equation",
    answer: "ᴬ_Z X → ᴬ⁻⁴_(Z−2) Y + ⁴₂α",
    detail: "The nucleus loses 2 protons and 2 neutrons; an alpha particle is a helium nucleus." },
  { id: "nuc-08", topic: "nuc", type: "formula", difficulty: 2,
    term: "Beta-minus decay",
    asks: "Give the general nuclear equation",
    answer: "ᴬ_Z X → ᴬ_(Z+1) Y + ⁰₋₁β + antineutrino",
    detail: "A neutron changes into a proton, emitting an electron and an electron antineutrino." },
  { id: "nuc-09", topic: "nuc", type: "formula", difficulty: 3,
    term: "Beta-plus decay",
    asks: "Give the general nuclear equation",
    answer: "ᴬ_Z X → ᴬ_(Z−1) Y + ⁰₊₁β + neutrino",
    detail: "A proton changes into a neutron, emitting a positron and an electron neutrino." },
  { id: "nuc-10", topic: "nuc", type: "definition", difficulty: 2,
    term: "Gamma emission",
    answer: "The emission of a high-energy photon when a nucleus loses excess energy; A and Z are unchanged.",
    detail: "Usually follows alpha or beta decay, which leaves the daughter nucleus in an excited state." },
  { id: "nuc-11", topic: "nuc", type: "theorem", difficulty: 2,
    term: "Ionising power and penetration of α, β, γ",
    answer: "Alpha: most ionising, stopped by paper. Beta: moderate, stopped by a few mm of aluminium. Gamma: least ionising, reduced by several cm of lead.",
    detail: "Ionising power and penetrating power run in opposite orders." },
  { id: "nuc-12", topic: "nuc", type: "definition", difficulty: 2,
    term: "Antiparticle",
    answer: "A particle with the same mass as its partner but opposite charge and opposite quantum numbers.",
    detail: "The positron is the antiparticle of the electron; a particle and its antiparticle annihilate on meeting." },
  { id: "nuc-13", topic: "nuc", type: "definition", difficulty: 2,
    term: "Quark composition of the proton and neutron",
    answer: "Proton = uud,  neutron = udd",
    detail: "Charges: u = +⅔e, d = −⅓e, giving +1e and 0 respectively." },
  { id: "nuc-14", topic: "nuc", type: "definition", difficulty: 2,
    term: "Charges of the up, down and strange quarks",
    answer: "u = +⅔e,  d = −⅓e,  s = −⅓e",
    detail: "Antiquarks carry the opposite charge, e.g. anti-up = −⅔e." },
  { id: "nuc-15", topic: "nuc", type: "definition", difficulty: 2,
    term: "Hadrons and leptons",
    answer: "Hadrons are particles made of quarks (protons, neutrons); leptons are fundamental particles that are not (electrons, neutrinos).",
    detail: "Baryons are hadrons made of three quarks; mesons are made of a quark-antiquark pair." },
  { id: "nuc-16", topic: "nuc", type: "theorem", difficulty: 3,
    term: "Beta-minus decay in terms of quarks",
    answer: "d → u + e⁻ + antineutrino",
    detail: "A down quark becomes an up quark, so udd (neutron) becomes uud (proton). Governed by the weak interaction." },
  { id: "nuc-17", topic: "nuc", type: "theorem", difficulty: 3,
    term: "Beta-plus decay in terms of quarks",
    answer: "u → d + e⁺ + neutrino",
    detail: "An up quark becomes a down quark, so uud (proton) becomes udd (neutron)." },
  { id: "nuc-18", topic: "nuc", type: "definition", difficulty: 3,
    term: "The weak interaction",
    answer: "The fundamental force responsible for beta decay, in which one flavour of quark changes into another.",
    detail: "The only interaction that can change quark flavour." },
  { id: "nuc-19", topic: "nuc", type: "definition", difficulty: 2,
    term: "Neutrino",
    answer: "A neutral lepton of negligible mass emitted in beta decay.",
    detail: "Proposed to conserve energy and momentum, since beta particles are emitted with a range of energies." },
  { id: "nuc-20", topic: "nuc", type: "unit", difficulty: 2,
    term: "The electronvolt",
    asks: "Give the value in joules",
    answer: "1 eV = 1.60 × 10⁻¹⁹ J",
    detail: "The energy gained by an electron accelerated through a p.d. of 1 V." },
  { id: "nuc-21", topic: "nuc", type: "unit", difficulty: 2,
    term: "Charge and mass of alpha, beta and gamma radiation",
    asks: "Give the charge and mass of each",
    answer: "α: +2e, 4u.  β⁻: −1e, ≈1/1840 u.  γ: no charge, no mass.",
    detail: "This is why α and β are deflected in electric and magnetic fields but γ is not." }

];

/* Convenience lookups used by app.js */
const TOPIC_BY_ID = TOPICS.reduce(function (acc, t) { acc[t.id] = t; return acc; }, {});
const CARD_BY_ID  = CARDS.reduce(function (acc, c) { acc[c.id] = c; return acc; }, {});
